# Generated by Django 3.1.7 on 2021-03-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210311_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='release_date_comment',
        ),
    ]
