# Generated by Django 3.1.7 on 2021-03-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_comment_release_date_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=250, verbose_name='Текст комментария'),
        ),
    ]
